### PR TITLE
Resolves #25, 37, #38, #39 Implemented friends page

### LINKED ISSUE #25: As an author, I want to befriend local authors

### PR DESCRIPTION
**Pull request by klindenbach**

### CODE REVIEW

**Comment by klindenbach** [comment]
screen shot 2015-03-06 at 2 27 39 am
screen shot 2015-03-06 at 2 27 55 am

**Comment by paul80** [comment]
No difference between this branch and the previous one called friends right?

**Comment by klindenbach** [comment]
Intent is the same. The other one had commits in the wrong order, so it was missing the addition to `urls.py`.

**Comment by paul80** [comment]
oh ok then. I guess i will merge yours first since your doesn't have conflicts and is longer.

**Pull request merged**
