### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by NBor**
This so that we have the basic proper packaging for this project. These changes allow you to run unit tests with "python setup.py nosetests" and install the project with "python setup.py install". Likely most people will want to use "python setup.py develop" and "python setup.py develop --uninstall" to save making new virtualenvs.

### CODE REVIEW

**Comment by klindenbach** [comment]
Ez_install looks like a library. You didn't write that yourself did you?

**Comment by NBor** [comment]
No, it comes from (https://pypi.python.org/pypi/setuptools). It is required for systems to bootstrap.

**Comment by klindenbach** [comment]
Just want to make sure it's license compatible. 

It should probably be added to the README too then.

**Comment by NBor** [comment]
I believe it falls under the same licensing as setuptools itself. "License: PSF or ZPL".
http://en.wikipedia.org/wiki/Python_Software_Foundation_License

**Comment by klindenbach** [comment]
Looks good

**Pull request merged**
