### PR TITLE
Paul branch2

### PR DESCRIPTION
**Pull request by paul80**
Can comment on posts inline now, login was restyled somewhat

### CODE REVIEW

**Comment by bigchipbag** [comment]
If a user makes a post, then comments on a post on the page that shows up immediately after the post is completed, two posts are sent to the server @paul80 this should be fixed
Shouldn't merge until we look at that

**Comment by bigchipbag** [comment]
Ok Here is the issue: You can only comment on one post on the page. And - say there are five posts on a page - with more than one post you can only make a comment on the bottom post, and it comments on that post the same number of times as there are posts visible on the page.
@paul80

**Comment by paul80** [comment]
Yeah you're right, I can replicate the problem, must of happened when moving the js out of home.html. Will fix soon

**Comment by paul80** [comment]
Sorry about the seemingly lazy fix but I haven't found something better yet

**Comment by bigchipbag** [comment]
Confirmed the issue is fixed and commenting inline works.

**Comment by bigchipbag** [comment]
I hit close by accident

**Pull request merged**
