### PR TITLE
added twitter bootstrap stuff inside the static folder, modified settings.py, urls.py and Ben's b...

### PR DESCRIPTION
**Pull request by paul80**
...ase and home html's to use it.

### CODE REVIEW

**Comment by klindenbach** [comment]
Why did we close this?

**Comment by paul80** [comment]
i closed this one because of changes to the templates_dir in settings.py that would allow for the use of a main project templates dir and a per app directory and because there was a 404 error on some icon that was fixed in a later branch of mine. 

TLDR: Didn't want someone to merge an older branch of mine

**Comment by klindenbach** [comment]
I c. Plans to re-up?

**Comment by paul80** [comment]
yup, adding some stuff to another branch called bootstrap_and_templates, didn't wanna mess with the bootstrap_css_stuff branch in case someone was using it.

**Comment by klindenbach** [comment]
Alright. Let me know

**Pull request closed without merging**
