### PR TITLE
addresses some ui issues mentioned, can change profile picture. fixes text overflow from panels in home page at least if someone something like this: "adkfklasljfsalkjfjksakjlfjksaklfljkslkjfdjsklfkljldsjaf....", pictures now displayed on friends.html 

### PR DESCRIPTION
**Pull request by paul80**
Will put up another pull request to address the authorhome page soon, so you guys can pick which one to merge and which one to not

### CODE REVIEW

**Comment by bigchipbag** [comment]
This is still broken.
http://imgur.com/a/3Fzrx
On an author's home page, the default picture is shown for posts
On the main stream page the logged in user;s photo is shown for every photo
The pictures on the friends page seems to work okay

**Comment by paul80** [comment]
yeah something is broken in it alright, closing this for now

**Comment by paul80** [comment]
ok it should be less broken at the very least. i didn't notice the issues you mentioned after this revision but its 3am so yeah

**Comment by paul80** [comment]
Ok tested some more this and it seems to work, heres authorpage:
authorpage1
Heres home stream:
homestream1
Here's friends.html page:
friends1

And yeah the authorpage should display the email and github of other authors now, provided the author is of our server. It doesn't show those fields for authors on other servers-  Was trying for authors on other servers but couldn't get it to work properly without returning none in the fields and whatnot. Up to you, however you wanna handle that issue though.

**Comment by paul80** [comment]
Also will work on centering images in posts later for aesthetic reasons

**Comment by klindenbach** [comment]
Sorry Paul. Seems too risky to merge at this point. It's mostly changes for profile pics which although cool and appreciated are not for marks. :(

**Pull request closed without merging**
