### PR TITLE
Applied Bootstrap and Fixed Nav Bar

### PR DESCRIPTION
**Pull request by jsurya**
- Installed Bootstrap into Login form
- Navigation Bar has been modified to model mockups

TODO:
- Align Login form
- Create form for search functionality

### CODE REVIEW

**Comment by klindenbach** [comment]
pics?

**Comment by jsurya** [comment]
image

**Comment by klindenbach** [comment]
What is the search bar for?

**Comment by jsurya** [comment]
For looking up other authors in the future

**Comment by klindenbach** [comment]
Before you sign in?

**Comment by klindenbach** [comment]
I thought that functionality was going to be on the `/friends` page

**Comment by jsurya** [comment]
I could remove it, I suppose.. looks awfully empty without it though

**Comment by klindenbach** [comment]
Looks ugly with it

**Comment by jsurya** [comment]
image

**Comment by klindenbach** [comment]
Sigh... You didn't actually change it?

**Pull request merged**
